/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 08-jul.-2021 06:08:41 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Chofer_Remitente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Chofer] DROP CONSTRAINT [FK_Chofer_Remitente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cliente_Localidad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Cliente_Localidad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ClienteTelefono_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ClienteTelefono] DROP CONSTRAINT [FK_ClienteTelefono_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Factura_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Factura] DROP CONSTRAINT [FK_Factura_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Factura_Localidad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Factura] DROP CONSTRAINT [FK_Factura_Localidad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_FacturaItem_Factura]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [FacturaItem] DROP CONSTRAINT [FK_FacturaItem_Factura]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_FacturaItem_Stock]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [FacturaItem] DROP CONSTRAINT [FK_FacturaItem_Stock]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Liquidacion_Stock]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Liquidacion] DROP CONSTRAINT [FK_Liquidacion_Stock]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Localidad_Provincia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Localidad] DROP CONSTRAINT [FK_Localidad_Provincia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Remitente_Banco]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Remitente] DROP CONSTRAINT [FK_Remitente_Banco]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Remitente_Localidad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Remitente] DROP CONSTRAINT [FK_Remitente_Localidad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Remitente_TipoCuenta]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Remitente] DROP CONSTRAINT [FK_Remitente_TipoCuenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_RemitenteProducto_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [RemitenteProducto] DROP CONSTRAINT [FK_RemitenteProducto_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_RemitenteProducto_Remitente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [RemitenteProducto] DROP CONSTRAINT [FK_RemitenteProducto_Remitente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Stock_Chofer]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Stock] DROP CONSTRAINT [FK_Stock_Chofer]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Stock_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Stock] DROP CONSTRAINT [FK_Stock_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Stock_Provincia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Stock] DROP CONSTRAINT [FK_Stock_Provincia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Stock_Remitente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Stock] DROP CONSTRAINT [FK_Stock_Remitente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Stock_Unidad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Stock] DROP CONSTRAINT [FK_Stock_Unidad]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Banco]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Banco]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Chofer]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Chofer]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ClienteTelefono]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ClienteTelefono]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Factura]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Factura]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FacturaItem]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [FacturaItem]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Liquidacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Liquidacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Localidad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Localidad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Provincia]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Provincia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Remitente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Remitente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[RemitenteProducto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [RemitenteProducto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Stock]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Stock]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TipoCuenta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TipoCuenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Unidad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Unidad]
GO

/* Create Tables */

CREATE TABLE [Banco]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Descripcion] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE [Chofer]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Nombre] VARCHAR(50) NOT NULL,
	[Apellido] VARCHAR(50) NOT NULL,
	[Dni] VARCHAR(15) NOT NULL,
	[IdRemitente] INT NOT NULL
)
GO

CREATE TABLE [Cliente]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Nombre] VARCHAR(255) NOT NULL,
	[Apellido] VARCHAR(255) NOT NULL,
	[Cuit] VARCHAR(255) NOT NULL,
	[IdCondicionIva] INT NOT NULL,
	[Domicilio] VARCHAR(MAX) NOT NULL,
	[idLocalidad] INT NOT NULL
)
GO

CREATE TABLE [ClienteTelefono]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[IdCliente] INT NOT NULL,
	[Telefono] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE [Factura]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[PuntoVenta] INT NOT NULL,
	[Letra] VARCHAR(1) NOT NULL,
	[Numero] INT NOT NULL,
	[Fecha] DATETIME NOT NULL,
	[IdCliente] INT NOT NULL,
	[Cuit] VARCHAR(15) NULL,
	[Domicilio] VARCHAR(255) NOT NULL,
	[IdLocalidad] INT NOT NULL,
	[NetoGravado] MONEY NOT NULL,
	[ImporteIva] MONEY NOT NULL,
	[DV] VARCHAR(32) NOT NULL
)
GO

CREATE TABLE [FacturaItem]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[IdFactura] INT NOT NULL,
	[Lote] INT NOT NULL,
	[Cantidad] INT NOT NULL,
	[PrecioUnitario] MONEY NOT NULL,
	[NetoGravado] MONEY NOT NULL,
	[ImporteIva] MONEY NOT NULL,
	[DV] VARCHAR(32) NOT NULL
)
GO

CREATE TABLE [Liquidacion]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Lote] INT NOT NULL,
	[CantidadVenta] INT NOT NULL,
	[CantidadDecomiso] INT NOT NULL,
	[PrecioPromedio] MONEY NOT NULL,
	[PrecioPlaza] MONEY NOT NULL,
	[PrecioLiquidado] MONEY NOT NULL,
	[ImporteComision] MONEY NOT NULL,
	[Pago] BIT NOT NULL,
	[DV] VARCHAR(32) NOT NULL
)
GO

CREATE TABLE [Localidad]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Descripcion] VARCHAR(50) NOT NULL,
	[IdProvincia] INT NOT NULL
)
GO

CREATE TABLE [Producto]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Descripcion] VARCHAR(255) NOT NULL,
	[Variedad] VARCHAR(255) NOT NULL,
	[Comision] MONEY NOT NULL,
	[Iva] MONEY NOT NULL
)
GO

CREATE TABLE [Provincia]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Descripcion] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE [Remitente]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Nombre] VARCHAR(255) NOT NULL,
	[Apellido] VARCHAR(255) NOT NULL,
	[Cuit] VARCHAR(255) NOT NULL,
	[IdCondicionIva] INT NOT NULL,
	[Domicilio] VARCHAR(MAX) NOT NULL,
	[IdLocalidad] INT NOT NULL,
	[IdBanco] INT NOT NULL,
	[Cuenta] VARCHAR(50) NOT NULL,
	[IdTipoCuenta] INT NOT NULL
)
GO

CREATE TABLE [RemitenteProducto]
(
	[IdRemitente] INT NOT NULL,
	[IdProducto] INT NOT NULL,
	[Comision] MONEY NOT NULL
)
GO

CREATE TABLE [Stock]
(
	[Lote] INT IDENTITY(1,1) NOT NULL,
	[IdRemitente] INT NOT NULL,
	[IdProducto] INT NOT NULL,
	[Origen] INT NOT NULL,
	[Fecha] DATETIME NOT NULL,
	[IdUnidad] INT NOT NULL,
	[Cantidad] decimal(18,2) NOT NULL,
	[Remanente] decimal(18,2) NOT NULL,
	[GuiaTransporte] VARCHAR(50) NOT NULL,
	[IdChofer] INT NOT NULL,
	[DV] VARCHAR(32) NOT NULL
)
GO

CREATE TABLE [TipoCuenta]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Descripcion] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE [Unidad]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Descripcion] VARCHAR(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Banco] 
 ADD CONSTRAINT [PK_Banco]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Chofer] 
 ADD CONSTRAINT [PK_Chofer]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Chofer_Remitente] 
 ON [Chofer] ([IdRemitente] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cliente_Localidad] 
 ON [Cliente] ([idLocalidad] ASC)
GO

ALTER TABLE [ClienteTelefono] 
 ADD CONSTRAINT [PK_ClienteTelefono]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_ClienteTelefono_Cliente] 
 ON [ClienteTelefono] ([IdCliente] ASC)
GO

ALTER TABLE [Factura] 
 ADD CONSTRAINT [PK_Factura]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Factura_Cliente] 
 ON [Factura] ([IdCliente] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Factura_Localidad] 
 ON [Factura] ([IdLocalidad] ASC)
GO

ALTER TABLE [FacturaItem] 
 ADD CONSTRAINT [PK_FacturaItem]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_FacturaItem_Factura] 
 ON [FacturaItem] ([IdFactura] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_FacturaItem_Stock] 
 ON [FacturaItem] ([Lote] ASC)
GO

ALTER TABLE [Liquidacion] 
 ADD CONSTRAINT [PK_Liquidacion]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Liquidacion_Stock] 
 ON [Liquidacion] ([Lote] ASC)
GO

ALTER TABLE [Localidad] 
 ADD CONSTRAINT [PK_Localidad]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Localidad_Provincia] 
 ON [Localidad] ([IdProvincia] ASC)
GO

ALTER TABLE [Producto] 
 ADD CONSTRAINT [PK_Producto]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Provincia] 
 ADD CONSTRAINT [PK_Provincia]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Remitente] 
 ADD CONSTRAINT [PK_Remitente]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Remitente_Banco] 
 ON [Remitente] ([IdBanco] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Remitente_Localidad] 
 ON [Remitente] ([IdLocalidad] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Remitente_TipoCuenta] 
 ON [Remitente] ([IdTipoCuenta] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_RemitenteProducto_Producto] 
 ON [RemitenteProducto] ([IdProducto] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_RemitenteProducto_Remitente] 
 ON [RemitenteProducto] ([IdRemitente] ASC)
GO

ALTER TABLE [Stock] 
 ADD CONSTRAINT [PK_Stock]
	PRIMARY KEY CLUSTERED ([Lote] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Stock_Chofer] 
 ON [Stock] ([IdChofer] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Stock_Producto] 
 ON [Stock] ([IdProducto] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Stock_Provincia] 
 ON [Stock] ([Origen] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Stock_Remitente] 
 ON [Stock] ([IdRemitente] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Stock_Unidad] 
 ON [Stock] ([IdUnidad] ASC)
GO

ALTER TABLE [TipoCuenta] 
 ADD CONSTRAINT [PK_TipoCuenta]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Unidad] 
 ADD CONSTRAINT [PK_Unidad]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Chofer] ADD CONSTRAINT [FK_Chofer_Remitente]
	FOREIGN KEY ([IdRemitente]) REFERENCES [Remitente] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Cliente_Localidad]
	FOREIGN KEY ([idLocalidad]) REFERENCES [Localidad] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ClienteTelefono] ADD CONSTRAINT [FK_ClienteTelefono_Cliente]
	FOREIGN KEY ([IdCliente]) REFERENCES [Cliente] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Factura] ADD CONSTRAINT [FK_Factura_Cliente]
	FOREIGN KEY ([IdCliente]) REFERENCES [Cliente] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Factura] ADD CONSTRAINT [FK_Factura_Localidad]
	FOREIGN KEY ([IdLocalidad]) REFERENCES [Localidad] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [FacturaItem] ADD CONSTRAINT [FK_FacturaItem_Factura]
	FOREIGN KEY ([IdFactura]) REFERENCES [Factura] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [FacturaItem] ADD CONSTRAINT [FK_FacturaItem_Stock]
	FOREIGN KEY ([Lote]) REFERENCES [Stock] ([Lote]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Liquidacion] ADD CONSTRAINT [FK_Liquidacion_Stock]
	FOREIGN KEY ([Lote]) REFERENCES [Stock] ([Lote]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Localidad] ADD CONSTRAINT [FK_Localidad_Provincia]
	FOREIGN KEY ([IdProvincia]) REFERENCES [Provincia] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Remitente] ADD CONSTRAINT [FK_Remitente_Banco]
	FOREIGN KEY ([IdBanco]) REFERENCES [Banco] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Remitente] ADD CONSTRAINT [FK_Remitente_Localidad]
	FOREIGN KEY ([IdLocalidad]) REFERENCES [Localidad] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Remitente] ADD CONSTRAINT [FK_Remitente_TipoCuenta]
	FOREIGN KEY ([IdTipoCuenta]) REFERENCES [TipoCuenta] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [RemitenteProducto] ADD CONSTRAINT [FK_RemitenteProducto_Producto]
	FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [RemitenteProducto] ADD CONSTRAINT [FK_RemitenteProducto_Remitente]
	FOREIGN KEY ([IdRemitente]) REFERENCES [Remitente] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Stock] ADD CONSTRAINT [FK_Stock_Chofer]
	FOREIGN KEY ([IdChofer]) REFERENCES [Chofer] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Stock] ADD CONSTRAINT [FK_Stock_Producto]
	FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Stock] ADD CONSTRAINT [FK_Stock_Provincia]
	FOREIGN KEY ([Origen]) REFERENCES [Provincia] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Stock] ADD CONSTRAINT [FK_Stock_Remitente]
	FOREIGN KEY ([IdRemitente]) REFERENCES [Remitente] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Stock] ADD CONSTRAINT [FK_Stock_Unidad]
	FOREIGN KEY ([IdUnidad]) REFERENCES [Unidad] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
