/*
-- Insert Permisos
-- Hay que calcular el DV
*/
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiArchivo', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiVehiculos', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiChoferes', 2, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiMaestros', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiCondicionesIva', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiProvincias', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiLocalidades', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiBancos', 2, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiTiposCuenta', 2, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiUnidades', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiRemitentes', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiProductos', 2, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiClientes', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiMovimientos', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiStock', 2, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiVentas', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiLiquidaciones', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiGestion', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiUsuarios', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiPermisos', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiBackup', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiBitacora', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiCambioContra', 3, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiSalir', 1, '')
INSERT INTO Permiso(Nombre, Criticidad, DV) VALUES('tsmiFamilias', 1, '')