/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 08-jul.-2021 06:06:20 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Leyendas_Idioma]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Leyendas] DROP CONSTRAINT [FK_Leyendas_Idioma]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Usuario_Idioma]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Usuario] DROP CONSTRAINT [FK_Usuario_Idioma]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_FamiliaPermiso_Familia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [FamiliaPermiso] DROP CONSTRAINT [FK_FamiliaPermiso_Familia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_FamiliaPermiso_Permiso]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [FamiliaPermiso] DROP CONSTRAINT [FK_FamiliaPermiso_Permiso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsuarioFamilia_Familia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsuarioFamilia] DROP CONSTRAINT [FK_UsuarioFamilia_Familia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsuarioFamilia_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsuarioFamilia] DROP CONSTRAINT [FK_UsuarioFamilia_Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsuarioPermiso_Permiso]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsuarioPermiso] DROP CONSTRAINT [FK_UsuarioPermiso_Permiso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsuarioPermiso_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsuarioPermiso] DROP CONSTRAINT [FK_UsuarioPermiso_Usuario]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Bitacora]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Bitacora]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Idioma]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Idioma]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Integridad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Integridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Leyendas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Leyendas]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Familia]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Familia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Permiso]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Permiso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FamiliaPermiso]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [FamiliaPermiso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UsuarioFamilia]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UsuarioFamilia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UsuarioPermiso]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UsuarioPermiso]
GO

/* Create Tables */

CREATE TABLE [Bitacora]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[FechaHora] DATETIME NOT NULL,
	[Patente] VARCHAR(256) NOT NULL,
	[Descripcion] VARCHAR(MAX) NOT NULL,
	[Criticidad] INT NOT NULL,
	[Login] VARCHAR(256) NOT NULL,
	[DV] VARCHAR(32) NOT NULL
)
GO

CREATE TABLE [Idioma]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Descripcion] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE [Integridad]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Tabla] VARCHAR(50) NOT NULL,
	[DV] VARCHAR(32) NOT NULL
)
GO

CREATE TABLE [Leyendas]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[IdIdioma] INT NOT NULL,
	[Modulo] VARCHAR(255) NOT NULL,
	[Tag] VARCHAR(255) NOT NULL,
	[Leyenda] VARCHAR(MAX) NOT NULL
)
GO

CREATE TABLE [Usuario]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Nombre] VARCHAR(50) NOT NULL,
	[Apellido] VARCHAR(50) NOT NULL,
	[Login] VARCHAR(256) NOT NULL,
	[Password] VARCHAR(256) NOT NULL,
	[Email] VARCHAR(256) NOT NULL,
	[IdIdioma] INT NOT NULL,
	[Activo] BIT NOT NULL,
	[Intentos] INT NOT NULL,
	[DV] VARCHAR(32) NOT NULL
)
GO

ALTER TABLE [Usuario]
    ADD CONSTRAINT DF_Usuario_Dv DEFAULT 0 FOR DV

CREATE TABLE [Familia]
(
	[Id] int IDENTITY(1, 1) NOT NULL,
	[Nombre] varchar(255) NOT NULL,
    [Activo] BIT NOT NULL
)
GO

CREATE TABLE [Permiso]
(
	[Id] int IDENTITY(1, 1) NOT NULL,
	[Nombre] varchar(255) NOT NULL,
    [Modulo] varchar(255) NOT NULL,
	[Criticidad] int NOT NULL
)
GO

CREATE TABLE [FamiliaPermiso]
(
	[IdFamilia] int NOT NULL,
	[IdPermiso] int NOT NULL,
    [IdTipoPermiso] int NULL, 
	[DV] varchar(32) NOT NULL
)
GO

CREATE TABLE [UsuarioFamilia]
(
	[IdUsuario] int NOT NULL,
	[IdFamilia] int NOT NULL,
	[DV] varchar(32) NOT NULL
)
GO

CREATE TABLE [UsuarioPermiso]
(
	[IdUsuario] int NULL,
	[IdPermiso] int NULL,
    [IdTipoPermiso] int NULL, 
	[DV] varchar(32) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Bitacora] 
 ADD CONSTRAINT [PK_Bitacora]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Idioma] 
 ADD CONSTRAINT [PK_Idioma]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Integridad] 
 ADD CONSTRAINT [PK_Integridad]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Leyendas] 
 ADD CONSTRAINT [PK_Leyendas]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Leyendas_Idioma] 
 ON [Leyendas] ([IdIdioma] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Usuario_Idioma] 
 ON [Usuario] ([IdIdioma] ASC)
GO

ALTER TABLE [Familia] 
 ADD CONSTRAINT [PK_Familia]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [FamiliaPermiso] 
 ADD CONSTRAINT [PK_FamiliaPermiso]
	PRIMARY KEY CLUSTERED ([IdFamilia] ASC,[IdPermiso] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_FamiliaPermiso_Familia] 
 ON [FamiliaPermiso] ([IdFamilia] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_FamiliaPermiso_Permiso] 
 ON [FamiliaPermiso] ([IdPermiso] ASC)
GO

ALTER TABLE [Permiso] 
 ADD CONSTRAINT [PK_Permiso]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [UsuarioFamilia] 
 ADD CONSTRAINT [PK_UsuarioFamilia]
	PRIMARY KEY CLUSTERED ([IdUsuario] ASC,[IdFamilia] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsuarioFamilia_Familia] 
 ON [UsuarioFamilia] ([IdFamilia] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsuarioFamilia_Usuario] 
 ON [UsuarioFamilia] ([IdUsuario] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsuarioPermiso_Permiso] 
 ON [UsuarioPermiso] ([IdPermiso] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsuarioPermiso_Usuario] 
 ON [UsuarioPermiso] ([IdUsuario] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Leyendas] ADD CONSTRAINT [FK_Leyendas_Idioma]
	FOREIGN KEY ([IdIdioma]) REFERENCES [Idioma] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Usuario] ADD CONSTRAINT [FK_Usuario_Idioma]
	FOREIGN KEY ([IdIdioma]) REFERENCES [Idioma] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [FamiliaPermiso] ADD CONSTRAINT [FK_FamiliaPermiso_Familia]
	FOREIGN KEY ([IdFamilia]) REFERENCES [Familia] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [FamiliaPermiso] ADD CONSTRAINT [FK_FamiliaPermiso_Permiso]
	FOREIGN KEY ([IdPermiso]) REFERENCES [Permiso] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UsuarioFamilia] ADD CONSTRAINT [FK_UsuarioFamilia_Familia]
	FOREIGN KEY ([IdFamilia]) REFERENCES [Familia] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UsuarioFamilia] ADD CONSTRAINT [FK_UsuarioFamilia_Usuario]
	FOREIGN KEY ([IdUsuario]) REFERENCES [Usuario] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UsuarioPermiso] ADD CONSTRAINT [FK_UsuarioPermiso_Permiso]
	FOREIGN KEY ([IdPermiso]) REFERENCES [Permiso] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UsuarioPermiso] ADD CONSTRAINT [FK_UsuarioPermiso_Usuario]
	FOREIGN KEY ([IdUsuario]) REFERENCES [Usuario] ([Id]) ON DELETE No Action ON UPDATE No Action
GO